//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnlineShopping.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBONLINESHOPPINGEntities : DbContext
    {
        public DBONLINESHOPPINGEntities()
            : base("name=DBONLINESHOPPINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLBasket> TBLBasket { get; set; }
        public virtual DbSet<TBLBrand> TBLBrand { get; set; }
        public virtual DbSet<TBLCategory> TBLCategory { get; set; }
        public virtual DbSet<TBLGender> TBLGender { get; set; }
        public virtual DbSet<TBLLike> TBLLike { get; set; }
        public virtual DbSet<TBLMember> TBLMember { get; set; }
        public virtual DbSet<TBLMessage> TBLMessage { get; set; }
        public virtual DbSet<TBLOrder> TBLOrder { get; set; }
        public virtual DbSet<TBLProduct> TBLProduct { get; set; }
        public virtual DbSet<TBLComments> TBLComments { get; set; }
        public virtual DbSet<TBLAddress> TBLAddress { get; set; }
        public virtual DbSet<TBLCargo> TBLCargo { get; set; }
    
        public virtual ObjectResult<Nullable<int>> total_number_of_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("total_number_of_products");
        }
    
        public virtual ObjectResult<Nullable<int>> total_number_of_brands()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("total_number_of_brands");
        }
    
        public virtual ObjectResult<Nullable<int>> total_number_of_categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("total_number_of_categories");
        }
    
        public virtual ObjectResult<string> active_member()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("active_member");
        }
    
        public virtual ObjectResult<string> brand_with_most_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("brand_with_most_products");
        }
    
        public virtual ObjectResult<string> category_with_most_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("category_with_most_products");
        }
    
        public virtual ObjectResult<string> most_liked_product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("most_liked_product");
        }
    
        public virtual ObjectResult<Nullable<int>> number_of_message()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("number_of_message");
        }
    
        public virtual ObjectResult<star_average_Result> star_average()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<star_average_Result>("star_average");
        }
    
        public virtual ObjectResult<string> best_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("best_products");
        }
    
        public virtual ObjectResult<Nullable<int>> best_like_product()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("best_like_product");
        }
    }
}
