//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnlineShopping.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdmin
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Authority { get; set; }
        public string Image { get; set; }
        public string Recovery { get; set; }
    }
}
