//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnlineShopping.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOrder
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Address { get; set; }
        public Nullable<int> Cargo { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Piece { get; set; }
        public string Size { get; set; }
    
        public virtual TBLMember TBLMember { get; set; }
        public virtual TBLAddress TBLAddress { get; set; }
        public virtual TBLCargo TBLCargo { get; set; }
        public virtual TBLProduct TBLProduct { get; set; }
    }
}
