//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOnlineShopping.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLProduct()
        {
            this.TBLBasket = new HashSet<TBLBasket>();
            this.TBLLike = new HashSet<TBLLike>();
            this.TBLComments = new HashSet<TBLComments>();
            this.TBLOrder = new HashSet<TBLOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> DateOfAdding { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public string Statement { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> Star { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLBasket> TBLBasket { get; set; }
        public virtual TBLBrand TBLBrand { get; set; }
        public virtual TBLCategory TBLCategory { get; set; }
        public virtual TBLGender TBLGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLLike> TBLLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLComments> TBLComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOrder> TBLOrder { get; set; }
    }
}
